/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TileImage {
        "alt": string;
        "src": string;
    }
}
declare global {
    interface HTMLTileImageElement extends Components.TileImage, HTMLStencilElement {
    }
    var HTMLTileImageElement: {
        prototype: HTMLTileImageElement;
        new (): HTMLTileImageElement;
    };
    interface HTMLElementTagNameMap {
        "tile-image": HTMLTileImageElement;
    }
}
declare namespace LocalJSX {
    interface TileImage {
        "alt"?: string;
        "onTile-image-click"?: (event: CustomEvent<any>) => void;
        "src"?: string;
    }
    interface IntrinsicElements {
        "tile-image": TileImage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tile-image": LocalJSX.TileImage & JSXBase.HTMLAttributes<HTMLTileImageElement>;
        }
    }
}
